services:
  uptime-kuna:
    image: louislam/uptime-kuma:1
    volumes:
      - ./app_data:/app/data
    labels:
      project: uptime-kuma
      service: uptime-kuma
    ports:
      - 3001:3001
    pull_policy: always
    restart: always